updated the tag name of the image
ONSdigital/census-rm-case-service pull request #4
Opened 2019-03-27 14:31 UTC by LukeLoze1

# Motivation and Context
When building locally the image is currently census-rm-casesvc, docker-dev looks for eu.gcr.io/census-rm-ci/rm/census-rm-casesvc.  So having this changes makes using locally easier

# What has changed
Change to tagging in pom.xml

# How to test?
Local copy, mvn clean install.
Then:  docker ps | grep casesvc
The latest image should be eu.gcr.io/census-rm-ci/rm/census-rm-casesvc

# Links
https://trello.com/c/8sVc2ua0/624-fix-built-image-name-for-casesvc

2019-03-28 08:44 UTC, hbrace approved these changes

2019-03-28 09:11 UTC, davidmort approved these changes

2019-03-28 11:54 UTC, AdeHarrison commented
do not merge yet

2019-03-28 11:56 UTC, AdeHarrison requested changes
Blocked due to travis build already prepending DOCKER_GCP_LOCATION to the image name, docker tag command fails but push still succeeds. We need an alternative to setting in pom file - maybe just document in docker dev to tag locally built images manually?

2019-04-01 12:39 UTC, AdamHawtin commented
@AdeHarrison Is there a reason not to just remove the re-tagging step from the travis script?

2019-04-03 09:10 UTC, AdamHawtin requested changes

2019-04-03 09:10 UTC, AdamHawtin commented on .travis.yml
> +  - update-image-tag
This should only be master?

2019-04-03 10:58 UTC, NickGrantONS commented on .travis.yml
> +  - DESTINATION_IMAGE_NAME="eu.gcr.io/census-rm-ci/rm//census-rm-casesvc"
Did you mean to have the double forward-slash in this image name?

2019-04-03 10:59 UTC, NickGrantX requested changes
See comment

2019-04-04 11:58 UTC, AdeHarrison approved these changes

2019-04-04 14:42 UTC, AdamHawtin approved these changes

2019-04-05 08:20 UTC, NickGrantONS commented on .travis.yml
> +    - DESTINATION_IMAGE_NAME="$DOCKER_GCP_LOCATION/census-rm-casesvc"
spacing

2019-04-05 08:21 UTC, NickGrantX approved these changes
would be good if you could tidy the spacing but no reason to block really

2019-04-05 08:53 UTC, merged