image location change
ONSdigital/census-rm-case-service pull request #6
Opened 2019-04-01 07:48 UTC by AdeHarrison

# Motivation and Context
integration tests  using old docker hub images

# What has changed
updated image location

# How to test?
checkout repo
docker-compose up
run tests

# Links
[Trello](https://trello.com/c/x27Xo9pW/627-case-service-integration-tests-using-old-sdcplatform-images)

2019-04-01 07:51 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [case service integration tests using old sdcplatform images](https://trello.com/c/x27Xo9pW/627-case-service-integration-tests-using-old-sdcplatform-images)

2019-04-01 08:06 UTC, jcox-dev approved these changes

2019-04-01 08:07 UTC, jcox-dev requested changes
Looks like we might be missing auth for travis to fetch images from GCR.

It might be as simple as running this line again before the `script`: https://github.com/ONSdigital/census-rm-case-service/blob/31615f15bc67e2aaebf27d034777aca7223e8173/.travis.yml#L22

2019-04-03 11:00 UTC, NickGrantX approved these changes
LGTM 👍

2019-04-03 14:45 UTC, jcox-dev approved these changes

2019-04-04 07:11 UTC, merged